substitutions:
  name: jbd-bms-ble
  device_description: "Monitor and control a Xiaoxiang Battery Management System (JBD-BMS) via BLE"
  external_components_source: github://syssi/esphome-jbd-bms@test-many-ble-connections

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jbd-bms"
    version: 2.1.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - id: client0
    mac_address: 70:3e:97:07:c0:01
  - id: client1
    mac_address: 70:3e:97:07:c0:02
  - id: client2
    mac_address: 70:3e:97:07:c0:03
  - id: client3
    mac_address: 70:3e:97:07:c0:04
  - id: client4
    mac_address: 70:3e:97:07:c0:05
  - id: client5
    mac_address: 70:3e:97:07:c0:06

jbd_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 2s
  - id: bms1
    ble_client_id: client1
    update_interval: 2s
  - id: bms2
    ble_client_id: client2
    update_interval: 2s
  - id: bms3
    ble_client_id: client3
    update_interval: 2s
  - id: bms4
    ble_client_id: client4
    update_interval: 2s
  - id: bms5
    ble_client_id: client5
    update_interval: 2s

sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    total_voltage:
      name: "bms0 total voltage"
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    total_voltage:
      name: "bms1 total voltage"
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms2
    total_voltage:
      name: "bms2 total voltage"
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms3
    total_voltage:
      name: "bms3 total voltage"
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms4
    total_voltage:
      name: "bms4 total voltage"
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms5
    total_voltage:
      name: "bms5 total voltage"

select:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    read_eeprom_register:
      name: "${bms0} read eeprom register"
      optionsmap:
        0xAA: "Error Counts"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    read_eeprom_register:
      name: "${bms1} read eeprom register"
      optionsmap:
        0xAA: "Error Counts"

switch:
  - platform: ble_client
    ble_client_id: client0
    name: "bms0 enable bluetooth connection"
    restore_mode: ALWAYS_OFF
  - platform: ble_client
    ble_client_id: client1
    name: "bms1 enable bluetooth connection"
    restore_mode: ALWAYS_OFF
  - platform: ble_client
    ble_client_id: client2
    name: "bms2 enable bluetooth connection"
    restore_mode: ALWAYS_OFF
  - platform: ble_client
    ble_client_id: client3
    name: "bms3 enable bluetooth connection"
    restore_mode: ALWAYS_OFF
  - platform: ble_client
    ble_client_id: client4
    name: "bms4 enable bluetooth connection"
    restore_mode: ALWAYS_OFF
  - platform: ble_client
    ble_client_id: client5
    name: "bms5 enable bluetooth connection"
    restore_mode: ALWAYS_OFF

binary_sensor:

text_sensor:

